{% set name = "pdfplumber" %}
{% set version = "0.11.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jsvine/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3a11a2fd7779a31cdabc46fba70014ddbddda1af89899b762a498aeda159a60f

build:
  number: 0
  entry_points:
    - pdfplumber = pdfplumber.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # Skip version lower then python 3.9, because pdfminer.six is avaliable only from python version 3.9
  # Skip version higher then python 3.11, because pypdfium2 is avaliable only from python version 3.9 to 3.11
  skip: True  # [py<39 or py>311]
  # Not found requested pypdfium2 >=4.18.0 on s390x
  skip: True  # [s390x]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - pdfminer.six ==20231228
    - pillow >=9.1
    - pypdfium2 >=4.18.0

{% set ignore_tests = "" %}
# Test runs forever
{% set ignore_tests = " --ignore=tests/test_issues.py" %}

{% set deselect_tests = "" %}
# The test pdf file missed in the tests/pdf folder
{% set deselect_tests = " --deselect=tests/test_display.py::Test::test_curves" %}
# raise Exception("Cannot find Ghostscript, which is required for repairs.\n")
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_from_issue_932" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_other_repair_inputs" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_repair_custom_path" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_repair_password" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_repair_setting" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_repair_to_file" %}
# PermissionError: [Errno 13] Permission denied: 'C:\\cygwin64\\tmp\\tmpv8cbmnp8
{% set deselect_tests = deselect_tests + " --deselect=tests/test_convert.py::Test::test_cli_csv" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_convert.py::Test::test_cli_csv_exclude" %} # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_convert.py::Test::test_cli_csv_include" %} # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_repair_setting" %} # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_repair.py::Test::test_repair_to_file" %} # [win]

test:
  source_files:
    - tests
  imports:
    - pdfplumber
  commands:
    # pip check cannot correctly determine the pdfminer-six library version: 
    # Error: pdfplumber 0.11.4 has requirement pdfminer.six==20231228, but you have pdfminer-six 0.0.1.
    # Package plan:
    # pdfminer.six:       20231228-py39hca03da5_0         sfe1ed40
    #- pip check
    - pdfplumber --help
    - pytest -vvv {{ ignore_tests }} {{ deselect_tests }} tests
  requires:
    - pip
    - pytest
    - pandas ==2.2.2

about:
  home: https://github.com/jsvine/pdfplumber
  summary: Plumb a PDF for detailed information about each char, rectangle, and line.
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  description: Plumb a PDF for detailed information about each text character, rectangle, and line. Plus - Table extraction and visual debugging.
  dev_url: https://github.com/jsvine/pdfplumber
  doc_url: https://github.com/jsvine/pdfplumber/blob/stable/README.md

extra:
  recipe-maintainers:
    - melonhead901
  skip-lints:
      - missing_pip_check
