{% set name = "pdfplumber" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfplumber-{{ version }}.tar.gz
  sha256: 696ad9d724ad3730c8bc46ed8977528bad63035a21fd42460f9ef9123e3c1675

build:
  number: 0
  entry_points:
    - pdfplumber = pdfplumber.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6.*
  run:
    - pdfminer.six ==20200517
    - pillow >=7.0.0
    - python >=3.6.*
    - wand

test:
  imports:
    - pdfplumber
  commands:
    - pip check
    - pdfplumber --help
  requires:
    - pip

about:
  home: https://github.com/jsvine/pdfplumber
  summary: Plumb a PDF for detailed information about each char, rectangle, and line.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
